/** Назва країни в UI → ISO 3166-1 alpha-2 (GeoNames, IP) */
export const COUNTRY_NAME_TO_ISO2: Record<string, string> = {
  Ukraine: 'UA',
  Poland: 'PL',
  Germany: 'DE',
  Spain: 'ES',
  France: 'FR',
  Italy: 'IT',
  'Czech Republic': 'CZ',
  Slovakia: 'SK',
  Hungary: 'HU',
  Romania: 'RO',
  Austria: 'AT',
  'United Kingdom': 'GB',
  Netherlands: 'NL',
  Belgium: 'BE',
  Portugal: 'PT',
  Greece: 'GR',
  Bulgaria: 'BG',
  Croatia: 'HR',
  Serbia: 'RS',
  Switzerland: 'CH',
  Kazakhstan: 'KZ',
  UAE: 'AE',
  USA: 'US',
  Canada: 'CA',
  Mexico: 'MX',
  Brazil: 'BR',
  Argentina: 'AR',
  Colombia: 'CO',
  Chile: 'CL',
  Peru: 'PE',
  Venezuela: 'VE',
  Ecuador: 'EC',
  Bolivia: 'BO',
  Paraguay: 'PY',
  Uruguay: 'UY',
  Panama: 'PA',
  'Costa Rica': 'CR',
  Guatemala: 'GT',
  Cuba: 'CU',
  'Dominican Republic': 'DO',
  'Puerto Rico': 'PR',
  Turkey: 'TR',
  Israel: 'IL',
  India: 'IN',
  China: 'CN',
  Japan: 'JP',
  'South Korea': 'KR',
  Australia: 'AU',
  'New Zealand': 'NZ',
  'South Africa': 'ZA',
  Egypt: 'EG',
  Nigeria: 'NG',
  Kenya: 'KE',
  Morocco: 'MA',
  'Saudi Arabia': 'SA',
  Qatar: 'QA',
  Sweden: 'SE',
  Norway: 'NO',
  Denmark: 'DK',
  Finland: 'FI',
  Ireland: 'IE',
  Lithuania: 'LT',
  Latvia: 'LV',
  Estonia: 'EE',
  Slovenia: 'SI',
  Moldova: 'MD',
  Georgia: 'GE',
  Armenia: 'AM',
  Azerbaijan: 'AZ',
}

/** ISO → назва (для IP-визначення країни) */
export const IP_COUNTRY_MAP: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_NAME_TO_ISO2).map(([name, iso]) => [iso, name]),
)

export function iso2ForCountry(countryName: string): string | undefined {
  return COUNTRY_NAME_TO_ISO2[countryName.trim()]
}
