/**
 * Spain-first MVP catalog for Documents & Procedures.
 *
 * RULE: Do NOT invent legal requirements, license rules, taxes, or contract clauses.
 * Entries with unverified legal content use status = under_review and
 * templateNeedsLegalReview = true. Official URLs only from known government portals.
 */

import type { DocumentRecord, FormFieldDef } from './types'

const BOE = {
  name: 'BOE — Agencia Estatal Boletín Oficial del Estado',
  url: 'https://www.boe.es/',
  lastVerified: '2026-08-13',
} as const

const AEAT = {
  name: 'Agencia Tributaria (AEAT)',
  url: 'https://sede.agenciatributaria.gob.es/',
  lastVerified: '2026-08-13',
} as const

const YOUR_EUROPE = {
  name: 'Your Europe — Business',
  url: 'https://europa.eu/youreurope/business/',
  lastVerified: '2026-08-13',
} as const

const DGT = {
  name: 'Dirección General de Tráfico (DGT)',
  url: 'https://www.dgt.es/',
  lastVerified: '2026-08-13',
} as const

const SEPE = {
  name: 'SEPE — Servicio Público de Empleo Estatal',
  url: 'https://www.sepe.es/',
  lastVerified: '2026-08-13',
} as const

const INCLUSION = {
  name: 'Ministerio de Inclusión, Seguridad Social y Migraciones',
  url: 'https://www.inclusion.gob.es/',
  lastVerified: '2026-08-13',
} as const

const repairContractFields: FormFieldDef[] = [
  { id: 'client_name', labelKey: 'docs.field.clientName', type: 'text', required: true, profileKey: 'full_name' },
  { id: 'client_phone', labelKey: 'docs.field.clientPhone', type: 'phone', profileKey: 'phone' },
  { id: 'client_email', labelKey: 'docs.field.clientEmail', type: 'email', profileKey: 'email' },
  { id: 'contractor_name', labelKey: 'docs.field.contractorName', type: 'text', required: true, profileKey: 'company_name' },
  { id: 'address', labelKey: 'docs.field.address', type: 'text', required: true, profileKey: 'location' },
  { id: 'work_description', labelKey: 'docs.field.workDescription', type: 'textarea', required: true },
  { id: 'materials', labelKey: 'docs.field.materials', type: 'textarea' },
  { id: 'price', labelKey: 'docs.field.price', type: 'number', required: true },
  { id: 'deadline', labelKey: 'docs.field.deadline', type: 'date' },
  { id: 'payment_terms', labelKey: 'docs.field.paymentTerms', type: 'textarea' },
  { id: 'warranty', labelKey: 'docs.field.warranty', type: 'textarea' },
  { id: 'extra_works', labelKey: 'docs.field.extraWorks', type: 'textarea' },
  { id: 'liability', labelKey: 'docs.field.liability', type: 'textarea' },
  { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
]

const rentalContractFields: FormFieldDef[] = [
  { id: 'landlord_name', labelKey: 'docs.field.landlordName', type: 'text', required: true },
  { id: 'tenant_name', labelKey: 'docs.field.tenantName', type: 'text', required: true, profileKey: 'full_name' },
  { id: 'property_address', labelKey: 'docs.field.propertyAddress', type: 'text', required: true },
  { id: 'rent_amount', labelKey: 'docs.field.rentAmount', type: 'number', required: true },
  { id: 'deposit', labelKey: 'docs.field.deposit', type: 'number' },
  { id: 'start_date', labelKey: 'docs.field.startDate', type: 'date', required: true },
  { id: 'end_date', labelKey: 'docs.field.endDate', type: 'date' },
  { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
]

const vehicleSaleFields: FormFieldDef[] = [
  { id: 'seller_name', labelKey: 'docs.field.sellerName', type: 'text', required: true },
  { id: 'buyer_name', labelKey: 'docs.field.buyerName', type: 'text', required: true, profileKey: 'full_name' },
  { id: 'vehicle_make', labelKey: 'docs.field.vehicleMake', type: 'text', required: true },
  { id: 'vehicle_model', labelKey: 'docs.field.vehicleModel', type: 'text', required: true },
  { id: 'vin', labelKey: 'docs.field.vin', type: 'text' },
  { id: 'plate', labelKey: 'docs.field.plate', type: 'text' },
  { id: 'price', labelKey: 'docs.field.price', type: 'number', required: true },
  { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
]

function esDoc(
  partial: Omit<DocumentRecord, 'countryCode' | 'countrySlug' | 'originalLanguage' | 'availableLanguages' | 'monetizationTier'> & {
    monetizationTier?: DocumentRecord['monetizationTier']
  },
): DocumentRecord {
  return {
    countryCode: 'ES',
    countrySlug: 'spain',
    originalLanguage: 'es',
    availableLanguages: ['es', 'en', 'uk'],
    monetizationTier: partial.monetizationTier ?? 'free',
    ...partial,
  }
}

/** Public catalog (Spain MVP). Expandable to DE/FR/… without changing UI. */
export const DOCUMENTS_CATALOG: DocumentRecord[] = [
  esDoc({
    id: 'es-residential-rental-contract',
    slug: 'residential-rental-contract',
    titleKey: 'docs.item.residentialRental.title',
    descriptionKey: 'docs.item.residentialRental.desc',
    subcategory: 'contracts-forms',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain (national) — verify regional rules',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
    formFields: rentalContractFields,
    templateNeedsLegalReview: true,
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.realEstate', searchQuery: 'real estate' },
    ],
    seoTitleKey: 'docs.item.residentialRental.seoTitle',
    seoDescriptionKey: 'docs.item.residentialRental.seoDesc',
  }),
  esDoc({
    id: 'es-alicante-residential-rental-contract',
    slug: 'residential-rental-contract',
    titleKey: 'docs.item.residentialRentalAlicante.title',
    descriptionKey: 'docs.item.residentialRentalAlicante.desc',
    subcategory: 'contracts-forms',
    region: 'Comunidad Valenciana',
    province: 'Alicante',
    city: 'Alicante',
    jurisdiction: 'Spain → Comunidad Valenciana → Alicante',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview', 'docs.req.regionalCheck'],
    formFields: rentalContractFields,
    templateNeedsLegalReview: true,
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
    ],
    seoTitleKey: 'docs.item.residentialRentalAlicante.seoTitle',
    seoDescriptionKey: 'docs.item.residentialRentalAlicante.seoDesc',
  }),
  esDoc({
    id: 'es-commercial-rental-contract',
    slug: 'commercial-rental-contract',
    titleKey: 'docs.item.commercialRental.title',
    descriptionKey: 'docs.item.commercialRental.desc',
    subcategory: 'contracts-forms',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain (national) — verify regional rules',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
    formFields: rentalContractFields,
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.commercialRental.seoTitle',
    seoDescriptionKey: 'docs.item.commercialRental.seoDesc',
  }),
  esDoc({
    id: 'es-property-purchase-contract',
    slug: 'property-purchase-contract',
    titleKey: 'docs.item.propertyPurchase.title',
    descriptionKey: 'docs.item.propertyPurchase.desc',
    subcategory: 'docs-real-estate',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.notary', 'docs.req.legalReview'],
    formFields: [
      { id: 'seller_name', labelKey: 'docs.field.sellerName', type: 'text', required: true },
      { id: 'buyer_name', labelKey: 'docs.field.buyerName', type: 'text', required: true, profileKey: 'full_name' },
      { id: 'property_address', labelKey: 'docs.field.propertyAddress', type: 'text', required: true },
      { id: 'price', labelKey: 'docs.field.price', type: 'number', required: true },
      { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
    ],
    templateNeedsLegalReview: true,
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.notary', searchQuery: 'notary', categorySlug: 'legal-notary' },
    ],
    seoTitleKey: 'docs.item.propertyPurchase.seoTitle',
    seoDescriptionKey: 'docs.item.propertyPurchase.seoDesc',
  }),
  esDoc({
    id: 'es-deposit-agreement',
    slug: 'deposit-agreement',
    titleKey: 'docs.item.deposit.title',
    descriptionKey: 'docs.item.deposit.desc',
    subcategory: 'contracts-forms',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: [
      { id: 'payer_name', labelKey: 'docs.field.payerName', type: 'text', required: true, profileKey: 'full_name' },
      { id: 'receiver_name', labelKey: 'docs.field.receiverName', type: 'text', required: true },
      { id: 'amount', labelKey: 'docs.field.amount', type: 'number', required: true },
      { id: 'purpose', labelKey: 'docs.field.purpose', type: 'textarea', required: true },
      { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
    ],
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.deposit.seoTitle',
    seoDescriptionKey: 'docs.item.deposit.seoDesc',
  }),
  esDoc({
    id: 'es-renovation-contract',
    slug: 'renovation-contract',
    titleKey: 'docs.item.renovation.title',
    descriptionKey: 'docs.item.renovation.desc',
    subcategory: 'construction-repair',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: repairContractFields,
    templateNeedsLegalReview: true,
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.construction', searchQuery: 'renovation' },
    ],
    seoTitleKey: 'docs.item.renovation.seoTitle',
    seoDescriptionKey: 'docs.item.renovation.seoDesc',
  }),
  esDoc({
    id: 'es-construction-contract',
    slug: 'construction-contract',
    titleKey: 'docs.item.construction.title',
    descriptionKey: 'docs.item.construction.desc',
    subcategory: 'construction-repair',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: repairContractFields,
    templateNeedsLegalReview: true,
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.construction', searchQuery: 'construction' },
    ],
    seoTitleKey: 'docs.item.construction.seoTitle',
    seoDescriptionKey: 'docs.item.construction.seoDesc',
  }),
  esDoc({
    id: 'es-subcontract-agreement',
    slug: 'subcontract-agreement',
    titleKey: 'docs.item.subcontract.title',
    descriptionKey: 'docs.item.subcontract.desc',
    subcategory: 'construction-repair',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: repairContractFields,
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.subcontract.seoTitle',
    seoDescriptionKey: 'docs.item.subcontract.seoDesc',
  }),
  esDoc({
    id: 'es-warranty-agreement',
    slug: 'warranty-agreement',
    titleKey: 'docs.item.warranty.title',
    descriptionKey: 'docs.item.warranty.desc',
    subcategory: 'construction-repair',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: [
      { id: 'provider_name', labelKey: 'docs.field.contractorName', type: 'text', required: true },
      { id: 'client_name', labelKey: 'docs.field.clientName', type: 'text', required: true, profileKey: 'full_name' },
      { id: 'scope', labelKey: 'docs.field.workDescription', type: 'textarea', required: true },
      { id: 'warranty', labelKey: 'docs.field.warranty', type: 'textarea', required: true },
      { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
    ],
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.warranty.seoTitle',
    seoDescriptionKey: 'docs.item.warranty.seoDesc',
  }),
  esDoc({
    id: 'es-work-completion-act',
    slug: 'work-completion-act',
    titleKey: 'docs.item.workAct.title',
    descriptionKey: 'docs.item.workAct.desc',
    subcategory: 'construction-repair',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: [
      { id: 'client_name', labelKey: 'docs.field.clientName', type: 'text', required: true, profileKey: 'full_name' },
      { id: 'contractor_name', labelKey: 'docs.field.contractorName', type: 'text', required: true },
      { id: 'work_description', labelKey: 'docs.field.workDescription', type: 'textarea', required: true },
      { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
    ],
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.construction', searchQuery: 'renovation' }],
    seoTitleKey: 'docs.item.workAct.seoTitle',
    seoDescriptionKey: 'docs.item.workAct.seoDesc',
  }),
  esDoc({
    id: 'es-handover-act',
    slug: 'handover-act',
    titleKey: 'docs.item.handover.title',
    descriptionKey: 'docs.item.handover.desc',
    subcategory: 'contracts-forms',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: [
      { id: 'party_a', labelKey: 'docs.field.partyA', type: 'text', required: true },
      { id: 'party_b', labelKey: 'docs.field.partyB', type: 'text', required: true, profileKey: 'full_name' },
      { id: 'object_desc', labelKey: 'docs.field.purpose', type: 'textarea', required: true },
      { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
    ],
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.handover.seoTitle',
    seoDescriptionKey: 'docs.item.handover.seoDesc',
  }),
  esDoc({
    id: 'es-vehicle-purchase-contract',
    slug: 'vehicle-purchase-contract',
    titleKey: 'docs.item.vehiclePurchase.title',
    descriptionKey: 'docs.item.vehiclePurchase.desc',
    subcategory: 'vehicles',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: DGT.lastVerified,
    source: DGT,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
    formFields: vehicleSaleFields,
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.vehiclePurchase.seoTitle',
    seoDescriptionKey: 'docs.item.vehiclePurchase.seoDesc',
  }),
  esDoc({
    id: 'es-vehicle-rental-contract',
    slug: 'vehicle-rental-contract',
    titleKey: 'docs.item.vehicleRental.title',
    descriptionKey: 'docs.item.vehicleRental.desc',
    subcategory: 'vehicles',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: null,
    source: DGT,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: vehicleSaleFields,
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.vehicleRental.seoTitle',
    seoDescriptionKey: 'docs.item.vehicleRental.seoDesc',
  }),
  esDoc({
    id: 'es-employment-contract',
    slug: 'employment-contract',
    titleKey: 'docs.item.employment.title',
    descriptionKey: 'docs.item.employment.desc',
    subcategory: 'work-professions',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: SEPE.lastVerified,
    source: SEPE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
    formFields: [
      { id: 'employer_name', labelKey: 'docs.field.employerName', type: 'text', required: true },
      { id: 'employee_name', labelKey: 'docs.field.employeeName', type: 'text', required: true, profileKey: 'full_name' },
      { id: 'job_title', labelKey: 'docs.field.jobTitle', type: 'text', required: true },
      { id: 'salary', labelKey: 'docs.field.salary', type: 'number' },
      { id: 'start_date', labelKey: 'docs.field.startDate', type: 'date' },
      { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
    ],
    templateNeedsLegalReview: true,
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.accountant', searchQuery: 'accountant', categorySlug: 'accounting-finance' },
    ],
    seoTitleKey: 'docs.item.employment.seoTitle',
    seoDescriptionKey: 'docs.item.employment.seoDesc',
  }),
  esDoc({
    id: 'es-services-agreement',
    slug: 'services-agreement',
    titleKey: 'docs.item.services.title',
    descriptionKey: 'docs.item.services.desc',
    subcategory: 'contracts-forms',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'contract_form',
    status: 'under_review',
    version: '2026.08-skeleton',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.legalReview'],
    formFields: repairContractFields,
    templateNeedsLegalReview: true,
    specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
    seoTitleKey: 'docs.item.services.seoTitle',
    seoDescriptionKey: 'docs.item.services.seoDesc',
  }),
  // —— Licenses (requirement level unknown until verified — never invent) ——
  esDoc({
    id: 'es-electrician-license',
    slug: 'electrician-license',
    titleKey: 'docs.item.electricianLicense.title',
    descriptionKey: 'docs.item.electricianLicense.desc',
    subcategory: 'licenses-permits',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain — may depend on activity and region',
    language: 'es',
    documentType: 'license',
    status: 'under_review',
    version: '2026.08-research',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.dependsOnActivity'],
    templateNeedsLegalReview: true,
    licenseRequirement: 'depends_on_activity',
    issuerKey: 'docs.issuer.verifyOfficial',
    costKey: 'docs.cost.verifyOfficial',
    durationKey: 'docs.duration.verifyOfficial',
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
    ],
    seoTitleKey: 'docs.item.electricianLicense.seoTitle',
    seoDescriptionKey: 'docs.item.electricianLicense.seoDesc',
  }),
  esDoc({
    id: 'es-alicante-electrician-license',
    slug: 'electrician-license',
    titleKey: 'docs.item.electricianLicenseAlicante.title',
    descriptionKey: 'docs.item.electricianLicenseAlicante.desc',
    subcategory: 'licenses-permits',
    region: 'Comunidad Valenciana',
    province: 'Alicante',
    city: 'Alicante',
    jurisdiction: 'Spain → Comunidad Valenciana → Alicante',
    language: 'es',
    documentType: 'license',
    status: 'under_review',
    version: '2026.08-research',
    effectiveDate: null,
    lastVerified: null,
    source: {
      name: 'Ajuntament d’Alacant / Ayuntamiento de Alicante',
      url: 'https://www.alicante.es/',
      lastVerified: null,
    },
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.dependsOnRegion'],
    templateNeedsLegalReview: true,
    licenseRequirement: 'depends_on_region',
    issuerKey: 'docs.issuer.verifyOfficial',
    costKey: 'docs.cost.verifyOfficial',
    durationKey: 'docs.duration.verifyOfficial',
    specialists: [
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
    ],
    seoTitleKey: 'docs.item.electricianLicenseAlicante.seoTitle',
    seoDescriptionKey: 'docs.item.electricianLicenseAlicante.seoDesc',
  }),
  esDoc({
    id: 'es-plumber-license',
    slug: 'plumber-license',
    titleKey: 'docs.item.plumberLicense.title',
    descriptionKey: 'docs.item.plumberLicense.desc',
    subcategory: 'licenses-permits',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain — may depend on activity and region',
    language: 'es',
    documentType: 'license',
    status: 'under_review',
    version: '2026.08-research',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource'],
    templateNeedsLegalReview: true,
    licenseRequirement: 'unknown',
    issuerKey: 'docs.issuer.verifyOfficial',
    specialists: [{ labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' }],
    seoTitleKey: 'docs.item.plumberLicense.seoTitle',
    seoDescriptionKey: 'docs.item.plumberLicense.seoDesc',
  }),
  esDoc({
    id: 'es-construction-permit',
    slug: 'construction-permit',
    titleKey: 'docs.item.constructionPermit.title',
    descriptionKey: 'docs.item.constructionPermit.desc',
    subcategory: 'licenses-permits',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain — municipal / regional',
    language: 'es',
    documentType: 'permit',
    status: 'under_review',
    version: '2026.08-research',
    effectiveDate: null,
    lastVerified: null,
    source: BOE,
    requirementsKeys: ['docs.req.dependsOnRegion', 'docs.req.verifyOfficialSource'],
    templateNeedsLegalReview: true,
    licenseRequirement: 'depends_on_region',
    issuerKey: 'docs.issuer.municipality',
    specialists: [
      { labelKey: 'docs.specialist.architect', searchQuery: 'architect' },
      { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
    ],
    seoTitleKey: 'docs.item.constructionPermit.seoTitle',
    seoDescriptionKey: 'docs.item.constructionPermit.seoDesc',
  }),
  // —— Business setup procedure ——
  esDoc({
    id: 'es-business-registration',
    slug: 'business-registration',
    titleKey: 'docs.item.businessReg.title',
    descriptionKey: 'docs.item.businessReg.desc',
    subcategory: 'start-business',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'procedure',
    status: 'active',
    version: '2026.08-pointer',
    effectiveDate: '2026-08-01',
    lastVerified: YOUR_EUROPE.lastVerified,
    source: YOUR_EUROPE,
    requirementsKeys: ['docs.req.verifyOfficialSource'],
    templateNeedsLegalReview: false,
    procedureSteps: [
      {
        id: 'legal-form',
        titleKey: 'docs.step.legalForm.title',
        bodyKey: 'docs.step.legalForm.body',
        whatIsKey: 'docs.step.legalForm.what',
        whatNeededKey: 'docs.step.legalForm.need',
        whereKey: 'docs.step.legalForm.where',
        source: YOUR_EUROPE,
      },
      {
        id: 'register',
        titleKey: 'docs.step.register.title',
        bodyKey: 'docs.step.register.body',
        source: YOUR_EUROPE,
      },
      {
        id: 'tax',
        titleKey: 'docs.step.tax.title',
        bodyKey: 'docs.step.tax.body',
        source: AEAT,
      },
      {
        id: 'social-security',
        titleKey: 'docs.step.ss.title',
        bodyKey: 'docs.step.ss.body',
        source: INCLUSION,
      },
      {
        id: 'licenses',
        titleKey: 'docs.step.licenses.title',
        bodyKey: 'docs.step.licenses.body',
        source: BOE,
      },
      {
        id: 'local',
        titleKey: 'docs.step.local.title',
        bodyKey: 'docs.step.local.body',
        source: BOE,
      },
    ],
    specialists: [
      { labelKey: 'docs.specialist.accountant', searchQuery: 'accountant', categorySlug: 'accounting-finance' },
      { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
      { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
    ],
    monetizationTier: 'business_setup',
    seoTitleKey: 'docs.item.businessReg.seoTitle',
    seoDescriptionKey: 'docs.item.businessReg.seoDesc',
  }),
  esDoc({
    id: 'es-alicante-business-registration',
    slug: 'business-registration',
    titleKey: 'docs.item.businessRegAlicante.title',
    descriptionKey: 'docs.item.businessRegAlicante.desc',
    subcategory: 'start-business',
    region: 'Comunidad Valenciana',
    province: 'Alicante',
    city: 'Alicante',
    jurisdiction: 'Spain → Comunidad Valenciana → Alicante',
    language: 'es',
    documentType: 'procedure',
    status: 'under_review',
    version: '2026.08-pointer',
    effectiveDate: null,
    lastVerified: YOUR_EUROPE.lastVerified,
    source: YOUR_EUROPE,
    requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.regionalCheck'],
    templateNeedsLegalReview: false,
    procedureSteps: [
      {
        id: 'legal-form',
        titleKey: 'docs.step.legalForm.title',
        bodyKey: 'docs.step.legalForm.body',
        source: YOUR_EUROPE,
      },
      {
        id: 'tax',
        titleKey: 'docs.step.tax.title',
        bodyKey: 'docs.step.tax.body',
        source: AEAT,
      },
      {
        id: 'local',
        titleKey: 'docs.step.local.title',
        bodyKey: 'docs.step.local.body',
        source: {
          name: 'Ajuntament d’Alacant / Ayuntamiento de Alicante',
          url: 'https://www.alicante.es/',
          lastVerified: null,
        },
      },
    ],
    specialists: [
      { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
      { labelKey: 'docs.specialist.accountant', searchQuery: 'accountant', categorySlug: 'accounting-finance' },
    ],
    monetizationTier: 'business_setup',
    seoTitleKey: 'docs.item.businessRegAlicante.seoTitle',
    seoDescriptionKey: 'docs.item.businessRegAlicante.seoDesc',
  }),
  esDoc({
    id: 'es-tax-procedures',
    slug: 'tax-procedures',
    titleKey: 'docs.item.taxProcedures.title',
    descriptionKey: 'docs.item.taxProcedures.desc',
    subcategory: 'taxes-finance',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'informational',
    status: 'active',
    version: '2026.08-pointer',
    effectiveDate: null,
    lastVerified: AEAT.lastVerified,
    source: AEAT,
    requirementsKeys: ['docs.req.verifyOfficialSource'],
    templateNeedsLegalReview: false,
    specialists: [
      { labelKey: 'docs.specialist.accountant', searchQuery: 'accountant', categorySlug: 'accounting-finance' },
    ],
    seoTitleKey: 'docs.item.taxProcedures.seoTitle',
    seoDescriptionKey: 'docs.item.taxProcedures.seoDesc',
  }),
  esDoc({
    id: 'es-residence-immigration',
    slug: 'residence-immigration',
    titleKey: 'docs.item.residence.title',
    descriptionKey: 'docs.item.residence.desc',
    subcategory: 'migration-residence',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'informational',
    status: 'active',
    version: '2026.08-pointer',
    effectiveDate: null,
    lastVerified: INCLUSION.lastVerified,
    source: INCLUSION,
    requirementsKeys: ['docs.req.verifyOfficialSource'],
    templateNeedsLegalReview: false,
    specialists: [
      { labelKey: 'docs.specialist.immigrationLawyer', searchQuery: 'immigration lawyer', categorySlug: 'legal-notary' },
    ],
    seoTitleKey: 'docs.item.residence.seoTitle',
    seoDescriptionKey: 'docs.item.residence.seoDesc',
  }),
  esDoc({
    id: 'es-government-procedures-entry',
    slug: 'government-procedures-entry',
    titleKey: 'docs.item.govProcedures.title',
    descriptionKey: 'docs.item.govProcedures.desc',
    subcategory: 'government-procedures',
    region: null,
    province: null,
    city: null,
    jurisdiction: 'Spain',
    language: 'es',
    documentType: 'informational',
    status: 'active',
    version: '2026.08-pointer',
    effectiveDate: null,
    lastVerified: BOE.lastVerified,
    source: BOE,
    requirementsKeys: ['docs.req.verifyOfficialSource'],
    templateNeedsLegalReview: false,
    specialists: [{ labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' }],
    seoTitleKey: 'docs.item.govProcedures.seoTitle',
    seoDescriptionKey: 'docs.item.govProcedures.seoDesc',
  }),
]

export const DOCUMENTS_SUBCATEGORY_ORDER: Array<{
  slug: import('./types').DocumentsSubcategorySlug
  icon: string
  titleKey: string
  descriptionKey: string
}> = [
  { slug: 'contracts-forms', icon: '📑', titleKey: 'docs.sub.contracts', descriptionKey: 'docs.sub.contracts.desc' },
  { slug: 'licenses-permits', icon: '🪪', titleKey: 'docs.sub.licenses', descriptionKey: 'docs.sub.licenses.desc' },
  { slug: 'start-business', icon: '🏢', titleKey: 'docs.sub.business', descriptionKey: 'docs.sub.business.desc' },
  { slug: 'docs-real-estate', icon: '🏠', titleKey: 'docs.sub.realEstate', descriptionKey: 'docs.sub.realEstate.desc' },
  { slug: 'vehicles', icon: '🚗', titleKey: 'docs.sub.vehicles', descriptionKey: 'docs.sub.vehicles.desc' },
  {
    slug: 'construction-repair',
    icon: '🔨',
    titleKey: 'docs.sub.construction',
    descriptionKey: 'docs.sub.construction.desc',
  },
  { slug: 'work-professions', icon: '💼', titleKey: 'docs.sub.work', descriptionKey: 'docs.sub.work.desc' },
  { slug: 'legal-matters', icon: '⚖️', titleKey: 'docs.sub.legal', descriptionKey: 'docs.sub.legal.desc' },
  { slug: 'taxes-finance', icon: '💰', titleKey: 'docs.sub.taxes', descriptionKey: 'docs.sub.taxes.desc' },
  { slug: 'migration-residence', icon: '🌍', titleKey: 'docs.sub.migration', descriptionKey: 'docs.sub.migration.desc' },
  {
    slug: 'government-procedures',
    icon: '📋',
    titleKey: 'docs.sub.government',
    descriptionKey: 'docs.sub.government.desc',
  },
  { slug: 'banks-finance', icon: '🏦', titleKey: 'docs.sub.banks', descriptionKey: 'docs.sub.banks.desc' },
  { slug: 'personal-documents', icon: '👨‍👩‍👧', titleKey: 'docs.sub.personal', descriptionKey: 'docs.sub.personal.desc' },
]
