/**
 * Generate Documents & Procedures packs for EU / EEA countries.
 * Uses official portal URLs from countrySources — never invents legal clauses.
 * lastVerified is null until OSM / human verification (do not seed fake dates).
 */

import { COUNTRY_SOURCES_BY_CODE, type CountrySourcesConfig } from '../officialSources/countrySources'
import {
  employmentFields,
  propertyPurchaseFields,
  repairContractFields,
  rentalContractFields,
  vehicleSaleFields,
} from './forms'
import { countrySlugFromCode } from './location'
import { withOfficialForm } from './officialForms'
import type { DocumentRecord } from './types'


const COUNTRY_NAME_UK: Record<string, string> = {
  ES: 'Іспанія',
  DE: 'Німеччина',
  FR: 'Франція',
  PL: 'Польща',
  IT: 'Італія',
  PT: 'Португалія',
  RO: 'Румунія',
  NL: 'Нідерланди',
  CZ: 'Чехія',
  HU: 'Угорщина',
  BG: 'Болгарія',
  AT: 'Австрія',
  SK: 'Словаччина',
  IE: 'Ірландія',
  SE: 'Швеція',
  DK: 'Данія',
  FI: 'Фінляндія',
  GR: 'Греція',
  BE: 'Бельгія',
  LU: 'Люксембург',
  LT: 'Литва',
  LV: 'Латвія',
  EE: 'Естонія',
  HR: 'Хорватія',
  SI: 'Словенія',
  CY: 'Кіпр',
  MT: 'Мальта',
  CH: 'Швейцарія',
  NO: 'Норвегія',
  UK: 'Велика Британія',
}

function src(name: string, url: string) {
  return { name, url, lastVerified: null }
}

function packForCountry(cfg: CountrySourcesConfig): DocumentRecord[] {
  const code = cfg.countryCode
  const slug = countrySlugFromCode(code) ?? code.toLowerCase()
  const name = cfg.countryName
  const nameUk = COUNTRY_NAME_UK[code] ?? name
  const gazette = src(`${name} official legislation`, cfg.officialGazetteUrl)
  const gov = src(`${name} government portal`, cfg.governmentPortalUrl || cfg.euPortalUrl)
  const tax = src(`${name} tax authority`, cfg.taxPortalUrl || cfg.governmentPortalUrl)
  const business = src('Your Europe — Business / national portal', cfg.businessPortalUrl || cfg.euPortalUrl)
  const eu = src('Your Europe', cfg.euPortalUrl)

  const base = (partial: Omit<DocumentRecord, 'countryCode' | 'countrySlug' | 'originalLanguage' | 'availableLanguages' | 'language' | 'monetizationTier'> & {
    monetizationTier?: DocumentRecord['monetizationTier']
    language?: string
  }): DocumentRecord => ({
    countryCode: code,
    countrySlug: slug,
    originalLanguage: 'en',
    availableLanguages: ['en', 'uk'],
    language: partial.language ?? 'en',
    monetizationTier: partial.monetizationTier ?? 'free',
    ...partial,
  })

  const lawyer = [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }]
  const accountant = [
    { labelKey: 'docs.specialist.accountant', searchQuery: 'accountant', categorySlug: 'accounting-finance' },
    { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
  ]

  return [
    base({
      id: `${slug}-business-registration`,
      slug: 'business-registration',
      titleKey: 'docs.tpl.businessReg.title',
      descriptionKey: 'docs.tpl.businessReg.desc',
      titleEn: `Start a business (${name})`,
      titleUk: `Відкрити бізнес (${nameUk})`,
      descriptionEn: `Official business setup pointers for ${name}. Verify on national / EU portals — not legal advice.`,
      descriptionUk: `Офіційні вказівники для відкриття бізнесу в країні: ${nameUk}. Перевіряйте на національних / EU порталах.`,
      subcategory: 'start-business',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'procedure',
      status: 'active',
      version: '2026.08-pointer',
      effectiveDate: '2026-08-01',
      lastVerified: null,
      source: business,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      procedureSteps: [
        {
          id: 'legal-form',
          titleKey: 'docs.step.legalForm.title',
          bodyKey: 'docs.step.legalForm.body',
          source: business,
        },
        {
          id: 'register',
          titleKey: 'docs.step.register.title',
          bodyKey: 'docs.step.register.body',
          source: gov,
        },
        {
          id: 'tax',
          titleKey: 'docs.step.tax.title',
          bodyKey: 'docs.step.tax.body',
          source: tax,
        },
        {
          id: 'licenses',
          titleKey: 'docs.step.licenses.title',
          bodyKey: 'docs.step.licenses.body',
          source: gazette,
        },
        {
          id: 'local',
          titleKey: 'docs.step.local.title',
          bodyKey: 'docs.step.local.body',
          source: gov,
        },
      ],
      specialists: [...accountant, ...lawyer],
      monetizationTier: 'business_setup',
      seoTitleKey: 'docs.tpl.businessReg.seoTitle',
      seoDescriptionKey: 'docs.tpl.businessReg.seoDesc',
    }),
    base({
      id: `${slug}-residential-rental-contract`,
      slug: 'residential-rental-contract',
      titleKey: 'docs.tpl.residentialRental.title',
      descriptionKey: 'docs.tpl.residentialRental.desc',
      titleEn: `Residential rental contract (${name})`,
      titleUk: `Договір оренди житла (${nameUk})`,
      descriptionEn: `Fillable skeleton for ${name}. Template requires legal review — not verified legal text.`,
      descriptionUk: `Заповнюваний скелет для ${nameUk}. Потребує юридичної перевірки.`,
      subcategory: 'contracts-forms',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
      formFields: rentalContractFields,
      templateNeedsLegalReview: true,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.residentialRental.seoTitle',
      seoDescriptionKey: 'docs.tpl.residentialRental.seoDesc',
    }),
    base({
      id: `${slug}-commercial-rental-contract`,
      slug: 'commercial-rental-contract',
      titleKey: 'docs.tpl.commercialRental.title',
      descriptionKey: 'docs.tpl.commercialRental.desc',
      titleEn: `Commercial rental contract (${name})`,
      titleUk: `Договір оренди комерційного приміщення (${nameUk})`,
      descriptionEn: `Skeleton under legal review for ${name}.`,
      descriptionUk: `Скелет на юридичній перевірці (${nameUk}).`,
      subcategory: 'contracts-forms',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.legalReview'],
      formFields: rentalContractFields,
      templateNeedsLegalReview: true,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.commercialRental.seoTitle',
      seoDescriptionKey: 'docs.tpl.commercialRental.seoDesc',
    }),
    base({
      id: `${slug}-property-purchase-contract`,
      slug: 'property-purchase-contract',
      titleKey: 'docs.tpl.propertyPurchase.title',
      descriptionKey: 'docs.tpl.propertyPurchase.desc',
      titleEn: `Property purchase contract (${name})`,
      titleUk: `Договір купівлі-продажу нерухомості (${nameUk})`,
      descriptionEn: `Skeleton — lawyer/notary review required (${name}).`,
      descriptionUk: `Скелет — потрібна перевірка юристом/нотаріусом (${nameUk}).`,
      subcategory: 'docs-real-estate',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.legalReview', 'docs.req.notary'],
      formFields: propertyPurchaseFields,
      templateNeedsLegalReview: true,
      specialists: [
        ...lawyer,
        { labelKey: 'docs.specialist.notary', searchQuery: 'notary', categorySlug: 'legal-notary' },
      ],
      seoTitleKey: 'docs.tpl.propertyPurchase.seoTitle',
      seoDescriptionKey: 'docs.tpl.propertyPurchase.seoDesc',
    }),
    base({
      id: `${slug}-renovation-contract`,
      slug: 'renovation-contract',
      titleKey: 'docs.tpl.renovation.title',
      descriptionKey: 'docs.tpl.renovation.desc',
      titleEn: `Renovation contract (${name})`,
      titleUk: `Договір ремонту (${nameUk})`,
      descriptionEn: `Fillable renovation skeleton for ${name}.`,
      descriptionUk: `Заповнюваний скелет договору ремонту (${nameUk}).`,
      subcategory: 'construction-repair',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.legalReview'],
      formFields: repairContractFields,
      templateNeedsLegalReview: true,
      specialists: [
        ...lawyer,
        { labelKey: 'docs.specialist.construction', searchQuery: 'renovation' },
      ],
      seoTitleKey: 'docs.tpl.renovation.seoTitle',
      seoDescriptionKey: 'docs.tpl.renovation.seoDesc',
    }),
    base({
      id: `${slug}-construction-contract`,
      slug: 'construction-contract',
      titleKey: 'docs.tpl.construction.title',
      descriptionKey: 'docs.tpl.construction.desc',
      titleEn: `Construction contract (${name})`,
      titleUk: `Договір підряду (${nameUk})`,
      descriptionEn: `Fillable construction skeleton for ${name}.`,
      descriptionUk: `Заповнюваний скелет договору підряду (${nameUk}).`,
      subcategory: 'construction-repair',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.legalReview'],
      formFields: repairContractFields,
      templateNeedsLegalReview: true,
      specialists: [
        ...lawyer,
        { labelKey: 'docs.specialist.construction', searchQuery: 'construction' },
      ],
      seoTitleKey: 'docs.tpl.construction.seoTitle',
      seoDescriptionKey: 'docs.tpl.construction.seoDesc',
    }),
    base({
      id: `${slug}-warranty-agreement`,
      slug: 'warranty-agreement',
      titleKey: 'docs.tpl.warranty.title',
      descriptionKey: 'docs.tpl.warranty.desc',
      titleEn: `Warranty agreement (${name})`,
      titleUk: `Гарантійний договір (${nameUk})`,
      descriptionEn: `Skeleton under legal review (${name}).`,
      descriptionUk: `Скелет на юридичній перевірці (${nameUk}).`,
      subcategory: 'construction-repair',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.legalReview'],
      formFields: [
        { id: 'provider_name', labelKey: 'docs.field.contractorName', type: 'text', required: true },
        { id: 'client_name', labelKey: 'docs.field.clientName', type: 'text', required: true, profileKey: 'full_name' },
        { id: 'scope', labelKey: 'docs.field.workDescription', type: 'textarea', required: true },
        { id: 'warranty', labelKey: 'docs.field.warranty', type: 'textarea', required: true },
        { id: 'signed_at', labelKey: 'docs.field.signedAt', type: 'date' },
      ],
      templateNeedsLegalReview: true,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.warranty.seoTitle',
      seoDescriptionKey: 'docs.tpl.warranty.seoDesc',
    }),
    base({
      id: `${slug}-vehicle-purchase-contract`,
      slug: 'vehicle-purchase-contract',
      titleKey: 'docs.tpl.vehiclePurchase.title',
      descriptionKey: 'docs.tpl.vehiclePurchase.desc',
      titleEn: `Vehicle purchase contract (${name})`,
      titleUk: `Договір купівлі-продажу авто (${nameUk})`,
      descriptionEn: `Skeleton — verify transfer steps on official portals (${name}).`,
      descriptionUk: `Скелет — перевірте переоформлення на офіційних порталах (${nameUk}).`,
      subcategory: 'vehicles',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gov,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
      formFields: vehicleSaleFields,
      templateNeedsLegalReview: true,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.vehiclePurchase.seoTitle',
      seoDescriptionKey: 'docs.tpl.vehiclePurchase.seoDesc',
    }),
    base({
      id: `${slug}-vehicle-purchase-commercial`,
      slug: 'vehicle-purchase-commercial',
      titleKey: 'docs.tpl.vehiclePurchaseCommercial.title',
      descriptionKey: 'docs.tpl.vehiclePurchaseCommercial.desc',
      titleEn: `Commercial vehicle purchase (${name})`,
      titleUk: `Купівля авто (комерційна) (${nameUk})`,
      descriptionEn: `B2B / VAT vehicle sale fields for ${name}. Complete official transfer + vehicle check portals.`,
      descriptionUk: `B2B / ПДВ поля купівлі авто для ${nameUk}. Оформлюйте офіційний трансфер і перевіряйте на держпорталах.`,
      subcategory: 'vehicles',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gov,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
      formFields: vehicleSaleFields,
      templateNeedsLegalReview: true,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.vehiclePurchaseCommercial.seoTitle',
      seoDescriptionKey: 'docs.tpl.vehiclePurchaseCommercial.seoDesc',
    }),
    base({
      id: `${slug}-employment-contract`,
      slug: 'employment-contract',
      titleKey: 'docs.tpl.employment.title',
      descriptionKey: 'docs.tpl.employment.desc',
      titleEn: `Employment contract (${name})`,
      titleUk: `Трудовий договір (${nameUk})`,
      descriptionEn: `Skeleton — verify with official labour / employment portals (${name}).`,
      descriptionUk: `Скелет — перевірте на офіційних трудових порталах (${nameUk}).`,
      subcategory: 'work-professions',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gov,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview'],
      formFields: employmentFields,
      templateNeedsLegalReview: true,
      specialists: [...lawyer, ...accountant],
      seoTitleKey: 'docs.tpl.employment.seoTitle',
      seoDescriptionKey: 'docs.tpl.employment.seoDesc',
    }),
    base({
      id: `${slug}-services-agreement`,
      slug: 'services-agreement',
      titleKey: 'docs.tpl.services.title',
      descriptionKey: 'docs.tpl.services.desc',
      titleEn: `Services agreement (${name})`,
      titleUk: `Договір надання послуг (${nameUk})`,
      descriptionEn: `Skeleton under legal review (${name}).`,
      descriptionUk: `Скелет на юридичній перевірці (${nameUk}).`,
      subcategory: 'contracts-forms',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.legalReview'],
      formFields: repairContractFields,
      templateNeedsLegalReview: true,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.services.seoTitle',
      seoDescriptionKey: 'docs.tpl.services.seoDesc',
    }),
    base({
      id: `${slug}-electrician-license`,
      slug: 'electrician-license',
      titleKey: 'docs.tpl.electricianLicense.title',
      descriptionKey: 'docs.tpl.electricianLicense.desc',
      titleEn: `Electrician license / permit (${name})`,
      titleUk: `Ліцензія / дозвіл електрика (${nameUk})`,
      descriptionEn: `May depend on activity and region in ${name}. Verify official source — not a definitive legal answer.`,
      descriptionUk: `Може залежати від діяльності та регіону в ${nameUk}. Перевірте офіційне джерело.`,
      subcategory: 'licenses-permits',
      region: null,
      province: null,
      city: null,
      jurisdiction: `${name} — may depend on activity and region`,
      documentType: 'license',
      status: 'under_review',
      version: '2026.08-research',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.dependsOnActivity'],
      templateNeedsLegalReview: true,
      licenseRequirement: 'depends_on_activity',
      issuerKey: 'docs.issuer.verifyOfficial',
      costKey: 'docs.cost.verifyOfficial',
      durationKey: 'docs.duration.verifyOfficial',
      specialists: [...lawyer, { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' }],
      seoTitleKey: 'docs.tpl.electricianLicense.seoTitle',
      seoDescriptionKey: 'docs.tpl.electricianLicense.seoDesc',
    }),
    base({
      id: `${slug}-plumber-license`,
      slug: 'plumber-license',
      titleKey: 'docs.tpl.plumberLicense.title',
      descriptionKey: 'docs.tpl.plumberLicense.desc',
      titleEn: `Plumber license / permit (${name})`,
      titleUk: `Ліцензія / дозвіл сантехніка (${nameUk})`,
      descriptionEn: `Unknown until verified for ${name} — open official source.`,
      descriptionUk: `Невідомо до перевірки (${nameUk}) — відкрийте офіційне джерело.`,
      subcategory: 'licenses-permits',
      region: null,
      province: null,
      city: null,
      jurisdiction: `${name} — may depend on activity and region`,
      documentType: 'license',
      status: 'under_review',
      version: '2026.08-research',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: true,
      licenseRequirement: 'unknown',
      issuerKey: 'docs.issuer.verifyOfficial',
      specialists: [{ labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' }],
      seoTitleKey: 'docs.tpl.plumberLicense.seoTitle',
      seoDescriptionKey: 'docs.tpl.plumberLicense.seoDesc',
    }),
    base({
      id: `${slug}-hvac-license`,
      slug: 'hvac-license',
      titleKey: 'docs.tpl.hvacLicense.title',
      descriptionKey: 'docs.tpl.hvacLicense.desc',
      titleEn: `HVAC / gas permit research (${name})`,
      titleUk: `Дозвіл HVAC / газ — дослідження (${nameUk})`,
      descriptionEn: `Requirement may depend on qualification and region in ${name}.`,
      descriptionUk: `Вимога може залежати від кваліфікації та регіону в ${nameUk}.`,
      subcategory: 'licenses-permits',
      region: null,
      province: null,
      city: null,
      jurisdiction: `${name} — depends on qualification / region`,
      documentType: 'license',
      status: 'under_review',
      version: '2026.08-research',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.dependsOnQualification', 'docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: true,
      licenseRequirement: 'depends_on_qualification',
      issuerKey: 'docs.issuer.verifyOfficial',
      specialists: [...lawyer, { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' }],
      seoTitleKey: 'docs.tpl.hvacLicense.seoTitle',
      seoDescriptionKey: 'docs.tpl.hvacLicense.seoDesc',
    }),
    base({
      id: `${slug}-construction-permit`,
      slug: 'construction-permit',
      titleKey: 'docs.tpl.constructionPermit.title',
      descriptionKey: 'docs.tpl.constructionPermit.desc',
      titleEn: `Construction / building permit (${name})`,
      titleUk: `Дозвіл на будівництво (${nameUk})`,
      descriptionEn: `Usually municipal / regional in ${name} — verify locally.`,
      descriptionUk: `Зазвичай муніципальний / регіональний у ${nameUk} — уточніть локально.`,
      subcategory: 'licenses-permits',
      region: null,
      province: null,
      city: null,
      jurisdiction: `${name} — municipal / regional`,
      documentType: 'permit',
      status: 'under_review',
      version: '2026.08-research',
      effectiveDate: null,
      lastVerified: null,
      source: gov,
      requirementsKeys: ['docs.req.dependsOnRegion', 'docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: true,
      licenseRequirement: 'depends_on_region',
      issuerKey: 'docs.issuer.municipality',
      specialists: [
        { labelKey: 'docs.specialist.architect', searchQuery: 'architect' },
        { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
      ],
      seoTitleKey: 'docs.tpl.constructionPermit.seoTitle',
      seoDescriptionKey: 'docs.tpl.constructionPermit.seoDesc',
    }),
    base({
      id: `${slug}-tax-procedures`,
      slug: 'tax-procedures',
      titleKey: 'docs.tpl.taxProcedures.title',
      descriptionKey: 'docs.tpl.taxProcedures.desc',
      titleEn: `Tax procedures (${name})`,
      titleUk: `Податкові процедури (${nameUk})`,
      descriptionEn: `Official tax portal entry for ${name} — no invented tax rules.`,
      descriptionUk: `Офіційний податковий портал (${nameUk}) — без вигаданих правил.`,
      subcategory: 'taxes-finance',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'informational',
      status: 'active',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: tax,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      specialists: accountant,
      seoTitleKey: 'docs.tpl.taxProcedures.seoTitle',
      seoDescriptionKey: 'docs.tpl.taxProcedures.seoDesc',
    }),
    base({
      id: `${slug}-residence-immigration`,
      slug: 'residence-immigration',
      titleKey: 'docs.tpl.residence.title',
      descriptionKey: 'docs.tpl.residence.desc',
      titleEn: `Residence & immigration (${name})`,
      titleUk: `Проживання та міграція (${nameUk})`,
      descriptionEn: `Official portal entry for ${name} / EU free movement info.`,
      descriptionUk: `Офіційний портал (${nameUk}) / інформація про вільне пересування в ЄС.`,
      subcategory: 'migration-residence',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'informational',
      status: 'active',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: eu,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      specialists: [
        {
          labelKey: 'docs.specialist.immigrationLawyer',
          searchQuery: 'immigration lawyer',
          categorySlug: 'legal-notary',
        },
      ],
      seoTitleKey: 'docs.tpl.residence.seoTitle',
      seoDescriptionKey: 'docs.tpl.residence.seoDesc',
    }),
    base({
      id: `${slug}-government-procedures-entry`,
      slug: 'government-procedures-entry',
      titleKey: 'docs.tpl.govProcedures.title',
      descriptionKey: 'docs.tpl.govProcedures.desc',
      titleEn: `Government procedures (${name})`,
      titleUk: `Державні процедури (${nameUk})`,
      descriptionEn: `Official legislation / government entry for ${name}.`,
      descriptionUk: `Офіційне законодавство / державний вхід (${nameUk}).`,
      subcategory: 'government-procedures',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'informational',
      status: 'active',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      specialists: [{ labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' }],
      seoTitleKey: 'docs.tpl.govProcedures.seoTitle',
      seoDescriptionKey: 'docs.tpl.govProcedures.seoDesc',
    }),
    base({
      id: `${slug}-legal-matters-entry`,
      slug: 'legal-matters-entry',
      titleKey: 'docs.tpl.legalMatters.title',
      descriptionKey: 'docs.tpl.legalMatters.desc',
      titleEn: `Legal matters entry (${name})`,
      titleUk: `Юридичні питання — вхід (${nameUk})`,
      descriptionEn: `Official legal / legislation portals for ${name}.`,
      descriptionUk: `Офіційні юридичні / законодавчі портали (${nameUk}).`,
      subcategory: 'legal-matters',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'informational',
      status: 'active',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.legalMatters.seoTitle',
      seoDescriptionKey: 'docs.tpl.legalMatters.seoDesc',
    }),
    base({
      id: `${slug}-banking-official-entry`,
      slug: 'banking-official-entry',
      titleKey: 'docs.tpl.banks.title',
      descriptionKey: 'docs.tpl.banks.desc',
      titleEn: `Banks & financial services (${name})`,
      titleUk: `Банки та фінансові послуги (${nameUk})`,
      descriptionEn: `Start from official government / EU consumer finance portals for ${name}.`,
      descriptionUk: `Почніть з офіційних урядових / EU порталів щодо фінансів (${nameUk}).`,
      subcategory: 'banks-finance',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'informational',
      status: 'under_review',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: gov,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      specialists: accountant,
      seoTitleKey: 'docs.tpl.banks.seoTitle',
      seoDescriptionKey: 'docs.tpl.banks.seoDesc',
    }),
    base({
      id: `${slug}-personal-documents-entry`,
      slug: 'personal-documents-entry',
      titleKey: 'docs.tpl.personal.title',
      descriptionKey: 'docs.tpl.personal.desc',
      titleEn: `Personal documents (${name})`,
      titleUk: `Особисті документи (${nameUk})`,
      descriptionEn: `Official civil-document portals for ${name} — no invented procedures.`,
      descriptionUk: `Офіційні портали особистих документів (${nameUk}) — без вигаданих процедур.`,
      subcategory: 'personal-documents',
      region: null,
      province: null,
      city: null,
      jurisdiction: name,
      documentType: 'informational',
      status: 'under_review',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: gov,
      requirementsKeys: ['docs.req.verifyOfficialSource'],
      templateNeedsLegalReview: false,
      specialists: lawyer,
      seoTitleKey: 'docs.tpl.personal.seoTitle',
      seoDescriptionKey: 'docs.tpl.personal.seoDesc',
    }),
  ]
}

/** City-level overlays (Germany Darmstadt etc.) — still pointers / under_review only. */
function cityOverlays(): DocumentRecord[] {
  const de = COUNTRY_SOURCES_BY_CODE.DE
  if (!de) return []
  const gazette = src('Gesetze im Internet', de.officialGazetteUrl)
  const business = src('Your Europe — Business', de.businessPortalUrl)
  return [
    {
      id: 'germany-darmstadt-business-registration',
      slug: 'business-registration',
      titleKey: 'docs.tpl.businessReg.title',
      descriptionKey: 'docs.tpl.businessReg.desc',
      titleEn: 'Start a business — Darmstadt (Hessen)',
      titleUk: 'Відкрити бізнес — Darmstadt (Hessen)',
      descriptionEn: 'National German steps plus local / state checks for Darmstadt. Verify official sources.',
      descriptionUk: 'Національні кроки Німеччини плюс місцеві / земельні перевірки для Darmstadt.',
      subcategory: 'start-business',
      countryCode: 'DE',
      countrySlug: 'germany',
      region: 'Hessen',
      province: 'Darmstadt',
      city: 'Darmstadt',
      jurisdiction: 'Germany → Hessen → Darmstadt',
      language: 'de',
      availableLanguages: ['de', 'en', 'uk'],
      originalLanguage: 'de',
      documentType: 'procedure',
      status: 'under_review',
      version: '2026.08-pointer',
      effectiveDate: null,
      lastVerified: null,
      source: business,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.regionalCheck'],
      templateNeedsLegalReview: false,
      procedureSteps: [
        { id: 'legal-form', titleKey: 'docs.step.legalForm.title', bodyKey: 'docs.step.legalForm.body', source: business },
        { id: 'tax', titleKey: 'docs.step.tax.title', bodyKey: 'docs.step.tax.body', source: src('ELSTER', de.taxPortalUrl) },
        { id: 'local', titleKey: 'docs.step.local.title', bodyKey: 'docs.step.local.body', source: src('Bund.de', de.governmentPortalUrl) },
      ],
      specialists: [
        { labelKey: 'docs.specialist.accountant', searchQuery: 'accountant', categorySlug: 'accounting-finance' },
        { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
      ],
      monetizationTier: 'business_setup',
      seoTitleKey: 'docs.tpl.businessReg.seoTitle',
      seoDescriptionKey: 'docs.tpl.businessReg.seoDesc',
    },
    {
      id: 'germany-darmstadt-residential-rental-contract',
      slug: 'residential-rental-contract',
      titleKey: 'docs.tpl.residentialRental.title',
      descriptionKey: 'docs.tpl.residentialRental.desc',
      titleEn: `Residential rental contract — Darmstadt`,
      titleUk: `Договір оренди житла — Darmstadt`,
      descriptionEn: `Jurisdiction: Germany → Hessen → Darmstadt. Skeleton under review.`,
      descriptionUk: `Юрисдикція: Німеччина → Hessen → Darmstadt. Скелет на перевірці.`,
      subcategory: 'contracts-forms',
      countryCode: 'DE',
      countrySlug: 'germany',
      region: 'Hessen',
      province: 'Darmstadt',
      city: 'Darmstadt',
      jurisdiction: 'Germany → Hessen → Darmstadt',
      language: 'de',
      availableLanguages: ['de', 'en', 'uk'],
      originalLanguage: 'de',
      documentType: 'contract_form',
      status: 'under_review',
      version: '2026.08-skeleton',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.legalReview', 'docs.req.regionalCheck'],
      formFields: rentalContractFields,
      templateNeedsLegalReview: true,
      specialists: [{ labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' }],
      monetizationTier: 'free',
      seoTitleKey: 'docs.tpl.residentialRental.seoTitle',
      seoDescriptionKey: 'docs.tpl.residentialRental.seoDesc',
    },
    {
      id: 'germany-darmstadt-electrician-license',
      slug: 'electrician-license',
      titleKey: 'docs.tpl.electricianLicense.title',
      descriptionKey: 'docs.tpl.electricianLicense.desc',
      titleEn: 'Electrician license — Darmstadt (Hessen)',
      titleUk: 'Ліцензія електрика — Darmstadt (Hessen)',
      descriptionEn:
        'Local/state requirement may differ in Hessen. Verify Chamber / state rules. (Germany)',
      descriptionUk:
        'Земельні вимоги Hessen можуть відрізнятися. Перевірте офіційні правила. (Німеччина)',
      subcategory: 'licenses-permits',
      countryCode: 'DE',
      countrySlug: 'germany',
      region: 'Hessen',
      province: 'Darmstadt',
      city: 'Darmstadt',
      jurisdiction: 'Germany → Hessen → Darmstadt',
      language: 'de',
      availableLanguages: ['de', 'en', 'uk'],
      originalLanguage: 'de',
      documentType: 'license',
      status: 'under_review',
      version: '2026.08-research',
      effectiveDate: null,
      lastVerified: null,
      source: gazette,
      requirementsKeys: ['docs.req.verifyOfficialSource', 'docs.req.dependsOnRegion'],
      templateNeedsLegalReview: true,
      licenseRequirement: 'depends_on_region',
      issuerKey: 'docs.issuer.verifyOfficial',
      specialists: [
        { labelKey: 'docs.specialist.lawyer', searchQuery: 'lawyer', categorySlug: 'legal-notary' },
        { labelKey: 'docs.specialist.gestor', searchQuery: 'gestor' },
      ],
      monetizationTier: 'free',
      seoTitleKey: 'docs.tpl.electricianLicense.seoTitle',
      seoDescriptionKey: 'docs.tpl.electricianLicense.seoDesc',
    },
  ]
}

/**
 * Build EU packs for all countries in countrySources.
 * Skip ES — detailed Spain catalog lives in catalog.ts.
 */
export function buildEuDocumentsCatalog(skipCodes: string[] = ['ES']): DocumentRecord[] {
  const skip = new Set(skipCodes.map((c) => c.toUpperCase()))
  const rows: DocumentRecord[] = []
  for (const cfg of Object.values(COUNTRY_SOURCES_BY_CODE)) {
    if (skip.has(cfg.countryCode.toUpperCase())) continue
    rows.push(...packForCountry(cfg).map(withOfficialForm))
  }
  rows.push(...cityOverlays().map(withOfficialForm))
  return rows
}
