import type { Company, CompanyDetail } from './types'

/** Client fallback when Supabase migration is not applied yet. */
export const FALLBACK_COMPANIES: Company[] = [
  {
    id: 'fb-bauhaus-berlin-group',
    owner_id: null,
    slug: 'bauhaus-berlin-group',
    name: 'Bauhaus Berlin Group',
    logo_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1400&h=500&fit=crop',
    short_description:
      'Full-cycle construction company for residential and commercial projects across Germany.',
    about:
      'Bauhaus Berlin Group delivers turnkey construction, from foundations to finishing. Our teams coordinate architects, engineers and certified trades under one contract.',
    category_slug: 'construction-companies',
    is_verified: true,
    is_premium: true,
    is_featured: true,
    rating: 4.9,
    reviews_count: 128,
    completed_projects: 340,
    employees_count: 85,
    founded_year: 2008,
    country_code: 'DE',
    country_name: 'Germany',
    city: 'Berlin',
    address: 'Alexanderplatz 1, Berlin',
    postal_code: null,
    latitude: 52.5219,
    longitude: 13.4132,
    languages: ['de', 'en', 'pl'],
    website: 'https://example.com/bauhaus-berlin',
    phone: '+49 30 123456',
    email: null,
    opening_hours: {
      timezone: 'Europe/Berlin',
      days: {
        mon: [['08:00', '18:00']],
        tue: [['08:00', '18:00']],
        wed: [['08:00', '18:00']],
        thu: [['08:00', '18:00']],
        fri: [['08:00', '17:00']],
      },
    },
    social: { linkedin: 'https://linkedin.com', instagram: 'https://instagram.com' },
    status: 'published',
    created_at: '2026-01-10T10:00:00Z',
    updated_at: '2026-06-01T10:00:00Z',
  },
  {
    id: 'fb-renova-madrid',
    owner_id: null,
    slug: 'renova-madrid',
    name: 'Renova Madrid',
    logo_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1400&h=500&fit=crop',
    short_description: 'Apartment and office renovations with fixed timelines and transparent budgets.',
    about: 'Specialists in kitchen, bathroom and full-flat renovations in Madrid.',
    category_slug: 'renovation-companies',
    is_verified: true,
    is_premium: false,
    is_featured: true,
    rating: 4.7,
    reviews_count: 86,
    completed_projects: 210,
    employees_count: 32,
    founded_year: 2014,
    country_code: 'ES',
    country_name: 'Spain',
    city: 'Madrid',
    address: 'Calle Gran Vía 28, Madrid',
    postal_code: null,
    latitude: 40.4203,
    longitude: -3.7058,
    languages: ['es', 'en'],
    website: 'https://example.com/renova-madrid',
    phone: '+34 91 555 0101',
    email: null,
    opening_hours: {
      timezone: 'Europe/Madrid',
      days: {
        mon: [['09:00', '19:00']],
        tue: [['09:00', '19:00']],
        wed: [['09:00', '19:00']],
        thu: [['09:00', '19:00']],
        fri: [['09:00', '18:00']],
        sat: [['10:00', '14:00']],
      },
    },
    social: { facebook: 'https://facebook.com' },
    status: 'published',
    created_at: '2026-02-01T10:00:00Z',
    updated_at: '2026-06-10T10:00:00Z',
  },
  {
    id: 'fb-atelier-nord',
    owner_id: null,
    slug: 'atelier-nord-architects',
    name: 'Atelier Nord Architects',
    logo_url: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=1400&h=500&fit=crop',
    short_description: 'Architecture studio focused on sustainable residential design.',
    about: 'Energy-efficient homes and mixed-use buildings with permitting support.',
    category_slug: 'architects',
    is_verified: true,
    is_premium: true,
    is_featured: false,
    rating: 4.8,
    reviews_count: 54,
    completed_projects: 96,
    employees_count: 18,
    founded_year: 2011,
    country_code: 'FR',
    country_name: 'France',
    city: 'Paris',
    address: '12 Rue de Rivoli, Paris',
    postal_code: null,
    latitude: 48.8556,
    longitude: 2.3608,
    languages: ['fr', 'en'],
    website: 'https://example.com/atelier-nord',
    phone: '+33 1 42 00 00 00',
    email: null,
    opening_hours: {
      timezone: 'Europe/Paris',
      days: {
        mon: [['09:00', '18:00']],
        tue: [['09:00', '18:00']],
        wed: [['09:00', '18:00']],
        thu: [['09:00', '18:00']],
        fri: [['09:00', '17:00']],
      },
    },
    social: { linkedin: 'https://linkedin.com' },
    status: 'published',
    created_at: '2026-01-20T10:00:00Z',
    updated_at: '2026-05-20T10:00:00Z',
  },
  {
    id: 'fb-buildmart',
    owner_id: null,
    slug: 'buildmart-materials-kyiv',
    name: 'BuildMart Materials',
    logo_url: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1400&h=500&fit=crop',
    short_description: 'Building materials warehouse with pro trade discounts.',
    about: 'Cement, drywall, insulation and delivery across Kyiv oblast.',
    category_slug: 'building-material-stores',
    is_verified: true,
    is_premium: false,
    is_featured: true,
    rating: 4.5,
    reviews_count: 210,
    completed_projects: 0,
    employees_count: 60,
    founded_year: 2009,
    country_code: 'UA',
    country_name: 'Ukraine',
    city: 'Kyiv',
    address: 'Peremohy Ave 45, Kyiv',
    postal_code: null,
    latitude: 50.4501,
    longitude: 30.5234,
    languages: ['uk', 'ru', 'en'],
    website: 'https://example.com/buildmart',
    phone: '+380 44 000 1122',
    email: null,
    opening_hours: {
      timezone: 'Europe/Kyiv',
      days: {
        mon: [['08:00', '19:00']],
        tue: [['08:00', '19:00']],
        wed: [['08:00', '19:00']],
        thu: [['08:00', '19:00']],
        fri: [['08:00', '19:00']],
        sat: [['09:00', '16:00']],
      },
    },
    social: {},
    status: 'published',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-06-15T10:00:00Z',
  },
  {
    id: 'fb-solara',
    owner_id: null,
    slug: 'solara-energy-lisbon',
    name: 'Solara Energy',
    logo_url: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=1400&h=500&fit=crop',
    short_description: 'Residential and commercial solar installation company.',
    about: 'Turnkey PV systems with monitoring and maintenance plans.',
    category_slug: 'solar-companies',
    is_verified: true,
    is_premium: true,
    is_featured: true,
    rating: 4.85,
    reviews_count: 112,
    completed_projects: 260,
    employees_count: 55,
    founded_year: 2012,
    country_code: 'PT',
    country_name: 'Portugal',
    city: 'Lisbon',
    address: 'Av. da Liberdade 100, Lisbon',
    postal_code: null,
    latitude: 38.7223,
    longitude: -9.1393,
    languages: ['pt', 'en', 'es'],
    website: 'https://example.com/solara',
    phone: '+351 21 000 0000',
    email: null,
    opening_hours: {
      timezone: 'Europe/Lisbon',
      days: {
        mon: [['09:00', '18:00']],
        tue: [['09:00', '18:00']],
        wed: [['09:00', '18:00']],
        thu: [['09:00', '18:00']],
        fri: [['09:00', '18:00']],
      },
    },
    social: { instagram: 'https://instagram.com', linkedin: 'https://linkedin.com' },
    status: 'published',
    created_at: '2026-01-05T10:00:00Z',
    updated_at: '2026-06-20T10:00:00Z',
  },
  {
    id: 'fb-nexus',
    owner_id: null,
    slug: 'nexus-smarthome',
    name: 'Nexus Smart Home',
    logo_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=1400&h=500&fit=crop',
    short_description: 'Smart lighting, security and home automation integrators.',
    about: 'KNX and Matter-ready installations for new builds and renovations.',
    category_slug: 'smart-home-companies',
    is_verified: true,
    is_premium: true,
    is_featured: true,
    rating: 4.88,
    reviews_count: 76,
    completed_projects: 140,
    employees_count: 26,
    founded_year: 2019,
    country_code: 'DE',
    country_name: 'Germany',
    city: 'Hamburg',
    address: 'Jungfernstieg 10, Hamburg',
    postal_code: null,
    latitude: 53.5534,
    longitude: 9.9922,
    languages: ['de', 'en'],
    website: 'https://example.com/nexus-smart',
    phone: '+49 40 111222',
    email: null,
    opening_hours: {
      timezone: 'Europe/Berlin',
      days: {
        mon: [['09:00', '18:00']],
        tue: [['09:00', '18:00']],
        wed: [['09:00', '18:00']],
        thu: [['09:00', '18:00']],
        fri: [['09:00', '17:00']],
      },
    },
    social: { linkedin: 'https://linkedin.com', youtube: 'https://youtube.com' },
    status: 'published',
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-07-01T10:00:00Z',
  },
  {
    id: 'fb-climateair',
    owner_id: null,
    slug: 'climate-air-brussels',
    name: 'ClimateAir HVAC',
    logo_url: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=1400&h=500&fit=crop',
    short_description: 'HVAC installation and heat-pump specialists.',
    about: 'Design, install and service ventilation and heating systems.',
    category_slug: 'hvac-suppliers',
    is_verified: true,
    is_premium: false,
    is_featured: true,
    rating: 4.75,
    reviews_count: 88,
    completed_projects: 175,
    employees_count: 40,
    founded_year: 2010,
    country_code: 'BE',
    country_name: 'Belgium',
    city: 'Brussels',
    address: 'Rue Neuve 15, Brussels',
    postal_code: null,
    latitude: 50.8503,
    longitude: 4.3517,
    languages: ['fr', 'nl', 'en'],
    website: 'https://example.com/climateair',
    phone: '+32 2 555 0101',
    email: null,
    opening_hours: {
      timezone: 'Europe/Brussels',
      days: {
        mon: [['08:00', '17:30']],
        tue: [['08:00', '17:30']],
        wed: [['08:00', '17:30']],
        thu: [['08:00', '17:30']],
        fri: [['08:00', '16:00']],
      },
    },
    social: {},
    status: 'published',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-05-30T10:00:00Z',
  },
  {
    id: 'fb-lumen',
    owner_id: null,
    slug: 'lumen-interior-milan',
    name: 'Lumen Interior Milan',
    logo_url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=200&h=200&fit=crop',
    cover_url: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=1400&h=500&fit=crop',
    short_description: 'Interior design studio for premium apartments and retail spaces.',
    about: 'Concept-to-install interior design with furniture sourcing.',
    category_slug: 'interior-design',
    is_verified: true,
    is_premium: true,
    is_featured: true,
    rating: 4.95,
    reviews_count: 73,
    completed_projects: 150,
    employees_count: 14,
    founded_year: 2016,
    country_code: 'IT',
    country_name: 'Italy',
    city: 'Milan',
    address: 'Via Montenapoleone 8, Milan',
    postal_code: null,
    latitude: 45.4685,
    longitude: 9.195,
    languages: ['it', 'en'],
    website: 'https://example.com/lumen-milan',
    phone: '+39 02 1234 5678',
    email: null,
    opening_hours: {
      timezone: 'Europe/Rome',
      days: {
        mon: [['10:00', '19:00']],
        tue: [['10:00', '19:00']],
        wed: [['10:00', '19:00']],
        thu: [['10:00', '19:00']],
        fri: [['10:00', '19:00']],
        sat: [['10:00', '14:00']],
      },
    },
    social: { instagram: 'https://instagram.com' },
    status: 'published',
    created_at: '2026-03-12T10:00:00Z',
    updated_at: '2026-06-22T10:00:00Z',
  },
]

export function enrichFallbackDetail(company: Company): CompanyDetail {
  return {
    ...company,
    services: [
      {
        id: `${company.id}-svc-1`,
        company_id: company.id,
        name: 'Core services',
        description: company.short_description,
        category_slug: company.category_slug,
        sort_order: 1,
      },
    ],
    gallery: company.cover_url
      ? [
          {
            id: `${company.id}-gal-1`,
            company_id: company.id,
            url: company.cover_url,
            caption: company.name,
            media_type: 'image',
            sort_order: 1,
          },
        ]
      : [],
    reviews: [
      {
        id: `${company.id}-rev-1`,
        company_id: company.id,
        reviewer_id: null,
        reviewer_name: 'Verified customer',
        rating: Math.round(company.rating),
        comment: 'Great experience working with this company.',
        is_verified: true,
        created_at: company.updated_at,
      },
    ],
    brands: [],
    team: [],
    certificates: company.is_verified
      ? [
          {
            id: `${company.id}-cert-1`,
            company_id: company.id,
            title: 'Verified on DImarket',
            issuer: 'DImarket',
            year: new Date().getFullYear(),
            document_url: null,
            sort_order: 1,
          },
        ]
      : [],
    licenses: [],
    portfolio: company.cover_url
      ? [
          {
            id: `${company.id}-port-1`,
            company_id: company.id,
            title: 'Featured project',
            description: company.short_description,
            image_url: company.cover_url,
            category_slug: company.category_slug,
            completed_at: null,
            sort_order: 1,
          },
        ]
      : [],
  }
}
